### ISSUE TITLE
Grafana 3.0 beta released

### ISSUE THREAD

**Issue by hablaras** [ab77/beastcraft-telemetry#1]
Hi Anton,

Great that you compiled Grafana for armhf (raspberry pi)! 

Since I cannot compile it myself and yours is about the only version I can find on the internet, would you also be willing to compile the latest version 3.0 beta as well?

Greetings,

Hablaras

**Comment by ab77** [comment]
I will once it is released as right now it is broken with regards to the latest InfluxDB.

**Comment by ab77** [comment]
https://github.com/ab77/beastcraft-telemetry/blob/master/grafana-armhf/README.md
